apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-kotlin-cicd-app
  namespace: apps
  labels:
    app: second-kotlin-cicd-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: second-kotlin-cicd-app
  template:
    metadata:
      labels:
        app: second-kotlin-cicd-app
    spec:
      containers:
        - name: second-kotlin-cicd-app
          image: registry.digitalocean.com/sa-container-registry-dev/second-kotlin-cicd-app:main-c25c63b-1640037809 # {"$imagepolicy": "flux-system:second-kotlin-cicd-app"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
      imagePullSecrets:
        - name: docker-cfg
