apiVersion: v1
kind: Service
metadata:
  name: second-kotlin-cicd-app
  namespace: apps
  labels:
    app: second-kotlin-cicd-app
spec:
  type: ClusterIP
  selector:
    app: second-kotlin-cicd-app
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http