apiVersion: v1
kind: Service
metadata:
  name: second-kotlin-cicd-app
  namespace: apps
  labels:
    app: second-kotlin-cicd-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
spec:
  type: ClusterIP
  selector:
    app: second-kotlin-cicd-app
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: http-actuator
      port: 8081
      protocol: TCP
      targetPort: http
