
spring:
  application:
    name: second-kotlin-cicd-app
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,refresh,info,prometheus