
spring:
  application:
    name: second-kotlin-cicd-app
  main:
    allow-bean-definition-overriding: true

# https://spring.io/blog/2020/03/25/liveness-and-readiness-probes-with-spring-boot
# https://arnoldgalovics.com/kubernetes-liveness-probe-spring-boot/
management:
  endpoint:
    prometheus:
      enabled: true
    restart:
      enabled: true
    health:
      enabled: true
      group:
        liveness:
          include: livenessstate,cacheCheck
      probes:
        enabled: true
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,refresh,info,prometheus

  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8081

server:
  port: 8080